---
- name: Clone user dotfiles
  git:
    repo: "{{ dotfiles.url }}"
    dest: /home/{{ user.name }}/{{ dotfiles.destination }}
    accept_hostkey: yes
    update: no
  when: dotfiles is defined
  become: yes
  become_user: "{{ user.name }}"
